---
title: "My Simple Logistic Regression"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
---
<hr />

<!-- Find some data of interest to you that can be analyzed with a logistic regression. Complete your Logistic Regression Analysis using this file. 

Hint, run the command 

> data() 

in your Console to see available datasets in R that you could use for this Analysis. You are also welcome to collect data yourself, or find other available datasets online for this Analysis. Just be careful to not use anyone else's "analysis" for this Analysis. Also, no conducting surveys unless you have IRB approval to do so. -->

```{r, include=FALSE}
library(mosaic)
library(ResourceSelection) 
library(DT)
```

```{r}
movies <- read.csv("../../Data/tmdb_5000_movies.csv", header=TRUE)
head(movies)
str(movies)
summary(movies)
# movies <- ggplot2movies::movies
```

<!-- for this analysis if you follow the outline of the challenger example you'll get an automatic 100% -->

#### Background
<insert background here>

```{r}
datatable(movies)
```

<br />

