---
title: "Chi Squared Test"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
---


<!-- Directions

Come up with a chi squared test analysis of your own creation. 

* Write the Background and clearly state your question. Then collect data and perform the linear regression analysis in order to answer your question. Use the proper order of first, ask the question, then second, figure out the answer.

* You can use data from 
    - An R data set
    - the internet (like weather data, Facebook data, or sports data) 
    - your own experiment 
    - your own observational study
* However,     
    - Do not violate the "Human Subjects Rules" of the university: http://www.byui.edu/executive-strategy-and-planning/institutional-research/research-and-assessments/research-and-surveys

* You need a sample size large enough to meet the requirements of the chi squared test. Unfortunately, the sample size is completely dependent on the situation you select. A good rule of thumb is 10 observations per "combination-group" in your data.

-->


## Background
<!-- text -->

## Hypothesis
<!-- text -->
$H_0 : \text{... are independent}$
$H_a : \text{... are associated (i.e. not independent)}$

We will use $\alpha = 0.05$ as our significance level.

## Analysis
<!-- text -->
```{r table of the data}

```

<!-- intro text -->
```{r barplot of the data}

```

<!-- intro text -->
```{r chi-squared test of the data}

```

<!-- intro text -->
```{r expected values table}

```
<!-- are the requirements met? -->
<!-- do we accept or reject the hypothesis? -->

<!-- intro text -->
```{r table of residuals}

```
<!-- explain residuals -->

## Interpretation
<!-- text -->

